import { useEffect, useState } from "react";

import {
  fetchSummary,
  generateSummary,
  updateSummary,
  type DailySummary,
} from "../../api";
import { useAuth } from "../../contexts/AuthContext";

interface DailySummaryCardProps {
  date: string;
  refreshKey: number;
  onChanged: () => void;
}

export default function DailySummaryCard({
  date,
  refreshKey,
  onChanged,
}: DailySummaryCardProps) {
  const { user } = useAuth();
  const [summary, setSummary] = useState<DailySummary | null>(null);
  const [content, setContent] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [isBusy, setIsBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setIsLoading(true);
    setError(null);
    fetchSummary(date)
      .then((dailySummary) => {
        setSummary(dailySummary);
        setContent(dailySummary?.content ?? "");
      })
      .catch((caught) => {
        setError(
          caught instanceof Error
            ? caught.message
            : "Could not load the summary",
        );
      })
      .finally(() => setIsLoading(false));
  }, [date, refreshKey]);

  async function save() {
    setIsBusy(true);
    setError(null);
    try {
      const saved = await updateSummary(date, content);
      setSummary(saved);
      onChanged();
    } catch (caught) {
      setError(
        caught instanceof Error ? caught.message : "Could not save the summary",
      );
    } finally {
      setIsBusy(false);
    }
  }

  async function generate() {
    const replaceEdited =
      summary?.is_user_edited === true &&
      window.confirm(
        "Replace your edited summary with a newly generated version?",
      );
    if (summary?.is_user_edited && !replaceEdited) return;

    setIsBusy(true);
    setError(null);
    try {
      const generated = await generateSummary(date, replaceEdited);
      setSummary(generated);
      setContent(generated.content);
      onChanged();
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "Could not generate the summary",
      );
    } finally {
      setIsBusy(false);
    }
  }

  return (
    <section
      aria-labelledby="daily-summary-title"
      className="rounded-lg border border-neutral-800 bg-neutral-950/50 p-5 lg:col-span-2"
    >
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2
            id="daily-summary-title"
            className="text-sm font-medium text-neutral-200"
          >
            Daily summary
          </h2>
          <p className="mt-1 text-xs text-neutral-500">
            Editable artifact · raw entries remain the source of truth
          </p>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={generate}
            disabled={
              isLoading || isBusy || !user?.ai_processing_consent
            }
            className="rounded-lg border border-violet-500/50 bg-violet-500/5 px-3 py-1.5 text-xs text-violet-300 transition-colors duration-150 hover:bg-violet-500/10 disabled:opacity-40"
          >
            Generate with NVIDIA
          </button>
          <button
            type="button"
            onClick={save}
            disabled={isLoading || isBusy}
            className="rounded-lg bg-neutral-800 px-3 py-1.5 text-xs text-neutral-200 transition-colors duration-150 hover:bg-neutral-700 disabled:opacity-40"
          >
            Save edits
          </button>
        </div>
      </div>

      {!user?.ai_processing_consent && (
        <p className="mt-3 text-xs text-neutral-600">
          External generation is off. Manual summaries remain available;
          enable AI in Settings if you want it.
        </p>
      )}

      <label
        htmlFor="daily-summary-content"
        className="sr-only"
      >
        Daily summary
      </label>
      <textarea
        id="daily-summary-content"
        value={content}
        disabled={isLoading}
        onChange={(event) => setContent(event.target.value)}
        placeholder={isLoading ? "Loading summary…" : "Summarize what moved, what was difficult, and what deserves continuation."}
        className="mt-4 min-h-32 w-full resize-y rounded-lg border border-neutral-800 bg-neutral-900 p-3 text-sm text-neutral-100 outline-none placeholder:text-neutral-600 focus:border-neutral-600 disabled:opacity-60"
      />

      {summary?.is_stale && (
        <p
          role="status"
          className="mt-2 rounded-lg border border-amber-900 bg-amber-950/30 px-3 py-2 text-xs leading-5 text-amber-300"
        >
          Source entries changed after this summary was saved. Save edits to
          make it current, or generate a new draft.
        </p>
      )}
      {summary && (
        <p className="mt-2 text-[11px] text-neutral-600">
          {summary.is_user_edited
            ? "Manually edited"
            : `Generated by ${summary.model ?? summary.provider}`}
          {" · "}
          source {summary.source_fingerprint.slice(0, 10)}
        </p>
      )}
      {error && (
        <p role="alert" className="mt-2 text-xs text-red-400">
          {error}
        </p>
      )}
    </section>
  );
}
